# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a62d01c095b3297cc893b5507ee0aefa3c1da78bbf69cc5058cd7280c93c2b56d2252162ea266316f7050a76aaf509ca584c471ccc8402f5cfae38576e671c1

test:
  secret_key_base: 0db8eaea90655bdd289acf03c4df2cbba974fe7dd127c70d27bec1651b86f8d4f3b41ece843728e6bd3b3d0eed7cad2b0edefcc3eab628a085d740b5cb47cec7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
